fix: correct calloc argument order in ft_strjoin
There was an error in the arrangement of arguments for calloc in ft_strjoin (dsl/src/utils.c).

Error: 'calloc' sizes specified with 'sizeof' in the previous argument and not in the later argument [-Werror=calloc-transposed-args]

Changed from calloc(sizeof(*s3), size) to calloc(size, sizeof(*s3)).